### ISSUE TITLE
Images for understanding

### ISSUE THREAD

**Issue by quinnliu** [Hunter690/catkin_ws#2]
![project_1](https://user-images.githubusercontent.com/2585159/27008301-b083b68c-4e33-11e7-9f70-24aceda23a25.png)

**Comment by quinnliu** [comment]
![y_neg_point_46](https://user-images.githubusercontent.com/2585159/27256895-82133fc4-5389-11e7-9f92-eb91e33b1ea3.png)

**Comment by Hunterzhaoliu** [comment]
![image](https://user-images.githubusercontent.com/24757872/27772884-acb29b1e-5f30-11e7-9bab-ed3402e1c2d6.png)
